'use strict';
const vm=require('node:vm');
const fs=require('node:fs');
const path=require('node:path');
for(const name of ['store','server','template','workflow-store','reliability','security','mail','import','demo','demo-cleanup','operations','commercial','integrations','postgres','postgres-worker','object-storage','production','continuity'])new vm.Script(fs.readFileSync(path.join(__dirname,'../portal/'+name+'.js'),'utf8'));
const html=require('../portal/template').buildPortal();
for(const match of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi))new vm.Script(match[1]);
if(/localStorage/.test(html))throw new Error('El portal no debe guardar datos privados en localStorage.');
if(/\bfincas?\b/i.test(html))throw new Error('Terminología antigua en el portal.');
console.log('Portal: integración V4, sintaxis y terminología comprobadas.');
