'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const os=require('node:os');
const crypto=require('node:crypto');
const {createPortal}=require('../portal/server');
const {Store}=require('../portal/store');
test('Real accounts, tenant isolation, archival, files, concurrency and recovery',async t=>{
  const directory=fs.mkdtempSync(path.join(os.tmpdir(),'marquee-portal-test-'));
  const recovery=fs.mkdtempSync(path.join(os.tmpdir(),'marquee-recovery-test-'));
  const env={APP_ORIGIN:'http://portal.test',DATA_DIR:directory,BOOTSTRAP_TOKEN:crypto.randomBytes(32).toString('hex')};
  let portal=createPortal({env,noAutomaticBackup:true});
  await new Promise(resolve=>portal.server.listen(0,'127.0.0.1',resolve));
  let base='http://127.0.0.1:'+portal.server.address().port;
  t.after(async()=>{await new Promise(resolve=>portal.server.close(resolve));fs.rmSync(directory,{recursive:true,force:true});fs.rmSync(recovery,{recursive:true,force:true});});
  function client(){return {cookie:'',csrf:'',async request(route,method='GET',body,headers={}){
    const response=await fetch(base+'/api'+route,{method,headers:{Origin:env.APP_ORIGIN,'Content-Type':'application/json',Cookie:this.cookie,'X-CSRF-Token':this.csrf,...headers},body:body===undefined?undefined:JSON.stringify(body)});
    const cookie=response.headers.get('set-cookie');if(cookie)this.cookie=cookie.split(';')[0];
    const type=response.headers.get('content-type')||'';const data=type.startsWith('application/json')?await response.json():Buffer.from(await response.arrayBuffer());
    if(data.csrf)this.csrf=data.csrf;return {status:response.status,data,headers:response.headers};
  }};}
  const a=client(),anonymous=client();
  const ok=async(promise,status=200)=>{const r=await promise;assert.equal(r.status,status,JSON.stringify(r.data));return r.data;};
  assert.equal((await anonymous.request('/state')).status,401);
  assert.equal((await a.request('/bootstrap','POST',{token:'bad',email:'info@marquee.es',firstName:'Admin',password:'initial-password-2026'})).status,403);
  await ok(a.request('/bootstrap','POST',{token:env.BOOTSTRAP_TOKEN,email:'info@marquee.es',firstName:'Admin',password:'initial-password-2026'}),201);
  assert.match(a.cookie,/marquee_session=/);assert.ok(a.csrf);
  assert.equal((await a.request('/bootstrap','POST',{token:env.BOOTSTRAP_TOKEN})).status,403);
  const initial=await ok(a.request('/state'));assert.equal(initial.data.events.length,0);assert.ok(!JSON.stringify(initial).includes('passwordHash'));assert.ok(!JSON.stringify(initial).includes('initial-password'));
  const protectedId=initial.data.users[0].id;assert.equal(initial.data.users[0].protectedAccount,true);
  for(const change of [{active:false},{role:'COMMERCIAL'},{email:'changed@example.test'},{venueId:'somewhere'}])assert.equal((await a.request('/users/'+protectedId,'PATCH',change)).status,403);
  await assert.rejects(()=>portal.store.provisionProtectedAdmin('replacement-password-2026'),{status:409});
  assert.equal((await a.request('/users/'+protectedId,'DELETE')).status,405);
  assert.equal((await a.request('/venues','POST',{name:'No CSRF'},{'X-CSRF-Token':'bad'})).status,403);
  assert.equal((await a.request('/venues','POST',{name:'Cross site'},{Origin:'https://evil.test'})).status,403);
  const space=async(name,email)=>ok(a.request('/venues-with-user','POST',{venue:{name,municipality:'Málaga'},user:{firstName:name,email}}));
  const first=await space('Espacio Uno','one@example.test'),second=await space('Espacio Dos','two@example.test');
  assert.equal(first.data.venues.length,1);assert.equal(second.data.venues.length,2);
  const one=client(),two=client();
  async function activate(c,account,email,password){await ok(c.request('/login','POST',{email,password:account.result.temporaryPassword}));assert.equal((await c.request('/state')).status,403);await ok(c.request('/password','POST',{currentPassword:account.result.temporaryPassword,password}));}
  await activate(one,first,'one@example.test','space-one-secret-2026');await activate(two,second,'two@example.test','space-two-secret-2026');
  const otherAdmin=await ok(a.request('/users','POST',{firstName:'Other admin',email:'other-admin@example.test',role:'ADMIN'}));
  const b=client();await activate(b,otherAdmin,'other-admin@example.test','other-admin-secret-2026');
  for(const change of [{active:false},{role:'VENUE_USER'},{email:'changed@example.test'},{password:'replacement-password-2026'}])assert.equal((await b.request('/users/'+protectedId,'PATCH',change)).status,403);
  let oneState=(await ok(one.request('/state'))).data;assert.equal(oneState.venues.length,1);assert.equal(oneState.venues[0].name,'Espacio Uno');assert.ok(!JSON.stringify(oneState).includes('two@example.test'));
  assert.equal((await one.request('/users','POST',{firstName:'Intruder',email:'intruder@example.test',role:'ADMIN'})).status,403);
  assert.equal((await one.request('/events','POST',{venueId:second.result.venue.id,eventName:'Wrong tenant',eventDate:'2027-05-01'})).status,403);
  assert.equal((await one.request('/events','POST',{eventName:'Bad date',eventDate:'2027-02-30'})).status,400);
  let event=(await ok(one.request('/events','POST',{eventName:'Convención Cliente Uno',eventDate:'2027-05-01',finalClient:'Empresa Recurrente',audiovisualRequest:'Sonido y pantalla',numberOfPeople:120}))).result;
  const eventId=event.id;
  const otherEvent=(await ok(two.request('/events','POST',{eventName:'Privado Espacio Dos',eventDate:'2027-06-01',finalClient:'Cliente Privado'}))).result;
  assert.equal((await two.request('/events/'+eventId,'PATCH',{eventName:'Attack',revision:event.revision})).status,404);
  assert.equal((await one.request('/events/'+eventId,'PATCH',{status:'CONFIRMED',revision:event.revision})).status,403);
  assert.equal((await one.request('/events/'+eventId,'PATCH',{eventName:'Stale',revision:999})).status,409);
  assert.equal((await one.request('/events/'+eventId+'/comments','POST',{internal:true,body:'Forbidden note'})).status,403);
  await ok(a.request('/events/'+eventId+'/comments','POST',{internal:true,body:'SECRET_INTERNAL_NOTE'}));
  await ok(one.request('/events/'+eventId+'/comments','POST',{body:'Mensaje del espacio'}));
  const pdf=Buffer.from('%PDF-1.4\n1 0 obj <</Type /Catalog>> endobj\n%%EOF');
  const upload=async(c,data)=>ok(c.request('/events/'+eventId+'/files','POST',{originalName:'presupuesto.pdf',base64:pdf.toString('base64'),...data}));
  const budget=(await upload(a,{kind:'budgets',status:'SENT',displayName:'Propuesta V1'})).result;
  const internalFile=(await upload(a,{kind:'documents',visibility:'INTERNAL',displayName:'INTERNAL_FILE'})).result;
  const document=(await upload(one,{kind:'documents',visibility:'INTERNAL',displayName:'Plano aportado'})).result;
  assert.equal(document.visibility,'SHARED');
  assert.equal((await one.request('/events/'+eventId+'/files','POST',{kind:'budgets',originalName:'forbidden.pdf',base64:pdf.toString('base64')})).status,403);
  assert.equal((await one.request('/events/'+eventId+'/files','POST',{kind:'documents',originalName:'wrong.pdf',base64:Buffer.from('<html>').toString('base64')})).status,400);
  const oneSerialized=JSON.stringify((await ok(one.request('/state'))).data);
  assert.ok(!oneSerialized.includes('SECRET_INTERNAL_NOTE'));assert.ok(!oneSerialized.includes('INTERNAL_FILE'));assert.ok(!oneSerialized.includes('Privado Espacio Dos'));assert.ok(!oneSerialized.includes('Cliente Privado'));
  assert.equal((await one.request('/files/'+internalFile.fileKey)).status,404);assert.equal((await two.request('/files/'+budget.fileKey)).status,404);assert.equal((await anonymous.request('/files/'+budget.fileKey)).status,401);
  assert.deepEqual((await ok(one.request('/files/'+budget.fileKey))),pdf);
  const refreshed=()=>ok(a.request('/state')).then(r=>r.data.events.find(e=>e.id===eventId));
  event=await refreshed();
  const [write1,write2]=await Promise.all([a.request('/events/'+eventId,'PATCH',{eventName:'Concurrent A',revision:event.revision}),a.request('/events/'+eventId,'PATCH',{eventName:'Concurrent B',revision:event.revision})]);
  assert.deepEqual([write1.status,write2.status].sort(),[200,409]);
  event=await refreshed();event=(await ok(a.request('/events/'+eventId,'PATCH',{status:'CONFIRMED',revision:event.revision}))).result;assert.ok(event.acceptedAt);
  const acceptedAt=event.acceptedAt;
  event=(await ok(a.request('/events/'+eventId,'PATCH',{status:'CANCELLED',revision:event.revision}))).result;
  assert.ok(event.archivedAt);assert.equal(event.deletedAt,null);assert.equal(event.acceptedAt,acceptedAt);assert.equal(event.budgets.length,1);assert.equal(event.documents.length,2);assert.equal(event.comments.length,1);assert.equal(event.internalNotes.length,1);
  assert.equal((await one.request('/events/'+eventId,'PATCH',{eventName:'Changed closed',revision:event.revision})).status,403);
  const cancelledView=(await ok(one.request('/state'))).data.events.find(e=>e.id===eventId);assert.equal(cancelledView.status,'CANCELLED');assert.equal(cancelledView.comments[0].body,'Mensaje del espacio');
  assert.deepEqual(await ok(one.request('/files/'+budget.fileKey)),pdf);
  let backup=await ok(a.request('/backups'));assert.ok(backup.backups.length>=1);
  const exportResult=await ok(a.request('/export?status=CANCELLED'));assert.equal(exportResult.payload.events.length,1);assert.equal(exportResult.payload.files.length,3);assert.equal(crypto.createHash('sha256').update(JSON.stringify(exportResult.payload)).digest('hex'),exportResult.sha256);
  assert.equal((await one.request('/export')).status,403);assert.equal((await one.request('/backups')).status,403);
  const snapshot=backup.backups[0];assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(directory,'backups',snapshot.filename))).digest('hex'),snapshot.sha256);
  fs.copyFileSync(path.join(directory,'backups',snapshot.filename),path.join(recovery,'marquee.sqlite'));
  const recovered=new Store(recovery);assert.equal(recovered.read().events.find(e=>e.id===eventId).status,'CANCELLED');assert.deepEqual(recovered.file(recovered.read().users.find(u=>u.email==='info@marquee.es'),budget.fileKey).bytes,pdf);recovered.close();
  event=(await ok(a.request('/events/'+eventId,'PATCH',{status:'PENDING_REVIEW',revision:event.revision}))).result;assert.equal(event.archivedAt,null);
  event=(await ok(a.request('/events/'+eventId,'PATCH',{status:'COMPLETED',revision:event.revision}))).result;assert.ok(event.completedAt);assert.equal(event.acceptedAt,acceptedAt);
  assert.equal((await a.request('/events/'+eventId,'DELETE')).status,405);
  await ok(a.request('/users/'+first.result.user.id,'PATCH',{active:false}));assert.equal((await one.request('/state')).status,401);
  assert.equal((await a.request('/state')).data.data.events.length,2);
  await new Promise(resolve=>portal.server.close(resolve));
  portal=createPortal({env,noAutomaticBackup:true});await new Promise(resolve=>portal.server.listen(0,'127.0.0.1',resolve));base='http://127.0.0.1:'+portal.server.address().port;
  const restarted=await ok(a.request('/state'));assert.equal(restarted.data.events.find(e=>e.id===eventId).status,'COMPLETED');assert.ok(restarted.data.events.find(e=>e.id===otherEvent.id));assert.deepEqual(await ok(a.request('/files/'+budget.fileKey)),pdf);
  const disk=fs.readFileSync(path.join(directory,'marquee.sqlite'));assert.ok(!disk.includes(Buffer.from('space-one-secret-2026')));assert.ok(!disk.includes(Buffer.from(first.result.temporaryPassword)));
  await ok(a.request('/logout','POST',{}));assert.equal((await a.request('/state')).status,401);
});
test('Production refuses ephemeral storage and missing setup secret',()=>{
  assert.throws(()=>createPortal({env:{NODE_ENV:'production',APP_ORIGIN:'https://portal.test'},noAutomaticBackup:true}),/persistente/);
  assert.throws(()=>createPortal({env:{RAILWAY_ENVIRONMENT_ID:'production',APP_ORIGIN:'https://portal.test',DATA_DIR:'/tmp/not-a-volume'},noAutomaticBackup:true}),/volumen/);
});
