  // Runs inside the original V4 scope so the approved components and navigation are reused.
  let portalCsrf=null, portalAccount=null, portalReady=false, portalSetup=false, portalBusy=false, portalDirty=false;
  let portalCredentials=null, portalBackupList=[], portalBackupError=null, portalSetupEmail='';
  const portalFilters={venue:'',from:'',to:'',q:''};
  const portalClosed=['CANCELLED','COMPLETED','NOT_ACCEPTED'];
  ensureV4Data=function(){
    for(const venue of app.data.venues){venue.technicalProfile=venue.technicalProfile||{};const fields=['spaces','loadingAccess','loadingHours','power','soundRestrictions','ceilingHeight','wifi','stage'];venue.technicalProfile.completeness=Math.round(fields.filter(k=>venue.technicalProfile[k]).length/fields.length*100);}
    for(const event of app.data.events){for(const key of ['budgets','documents','comments','internalNotes','history','tasks','infoRequests','readBy'])event[key]=event[key]||[];event.operationalTimes=event.operationalTimes||{};event.eventType=event.eventType||'OTHER';for(const budget of event.budgets){budget.expiryDate=budget.validUntil||budget.expiryDate||'';budget.viewedBy=budget.viewedBy||[];budget.downloadedBy=budget.downloadedBy||[];}}
  };
  let portalSetupToken=new URLSearchParams(location.hash.slice(1)).get('setup')||'';
  if(portalSetupToken)history.replaceState(null,'',location.pathname);
  async function portalApi(route,method='GET',data) {
    const response=await fetch('/api'+route,{method,credentials:'same-origin',headers:{...(data===undefined?{}:{'Content-Type':'application/json'}),...(portalCsrf?{'X-CSRF-Token':portalCsrf}:{})},body:data===undefined?undefined:JSON.stringify(data)});
    const result=await response.json();
    if(!response.ok){if(response.status===401&&route!=='/login'){portalAccount=null;app.session=null;app.data=loadData();portalMemoryValues.clear();renderShell();}throw Object.assign(new Error(result.error||'No se pudo completar la operación.'),{status:response.status});}
    return result;
  }
  async function portalReload(render=true) {
    if(!portalAccount||portalAccount.mustChangePassword)return;
    const {data}=await portalApi('/state');app.data=data;app.session={userId:portalAccount.id};
    // These V4 defaults are display-only. No demo records or automatic browser backups are loaded.
    ensureV4Data();if(render)renderShell();
  }
  async function portalRun(work,message) {
    if(portalBusy)return;
    portalBusy=true;document.body.classList.add('portal-busy');
    const buttons=[...document.querySelectorAll('button[type="submit"], [data-action="submit-external-form"]')];buttons.forEach(b=>b.disabled=true);
    try{const result=await work();portalDirty=false;if(message)toast(message,'Guardado en el espacio compartido.','success');return result;}
    catch(error){toast('No se pudo completar',error.message,'error');const box=document.getElementById('login-error');if(box){box.style.display='block';box.textContent=error.message;}}
    finally{portalBusy=false;document.body.classList.remove('portal-busy');buttons.forEach(b=>b.disabled=false);auditUpdateConnection();}
  }
  async function portalMutation(route,method,data) {
    const result=await portalApi(route,method,data);
    if(result.data){app.data=result.data;ensureV4Data();}
    if(result.backupWarning)toast('Revisar copia de recuperación',result.backupWarning,'warning');
    return result.result;
  }
  const portalOriginalLogin=renderLogin;
  renderLogin=function(){
    portalOriginalLogin();
    document.querySelector('.v4-version-pill').textContent='FLOW V4 · ESPACIO COMPARTIDO';
    document.querySelector('.login-legal').textContent='MARQUEE PRODUCCIONES Y AUDIOVISUALES, S.L.';
    document.querySelector('.v4-login-proof').innerHTML='<div><strong>Un expediente</strong><span>por cada evento</span></div><div><strong>Histórico completo</strong><span>también al cerrar el evento</span></div>';
    const card=document.querySelector('.v4-login-card');card.querySelector('.demo-profiles')?.remove();
    card.querySelector('h2').textContent=!portalReady?'Conectando…':portalAccount?.mustChangePassword?'Crea tu contraseña':portalSetup?'Activa Marquee Flow':'Tu espacio de eventos';
    card.querySelector('h2 + p').textContent=portalAccount?.mustChangePassword?'Sustituye la contraseña temporal para acceder a tu espacio.':portalSetup?'Configura la primera cuenta de administración.':'Accede con la cuenta que te ha facilitado el equipo de Marquee.';
    const form=card.querySelector('form');
    if(!portalReady){form.innerHTML='<p class="muted">Comprobando tu sesión…</p>';}
    else if(portalSetup&&!portalSetupToken){form.innerHTML='<div class="portal-notice">El portal está pendiente de activación. Abre el enlace de configuración facilitado a administración.</div>';}
    else if(portalAccount?.mustChangePassword){form.id='portal-password-form';form.innerHTML='<div><label class="label" for="current-password">Contraseña temporal</label><input class="field" id="current-password" name="currentPassword" type="password" autocomplete="current-password" required></div><div><label class="label" for="new-password">Nueva contraseña</label><input class="field" id="new-password" name="password" type="password" autocomplete="new-password" minlength="12" maxlength="128" required></div><div><label class="label" for="confirm-password">Repite la nueva contraseña</label><input class="field" id="confirm-password" name="confirmPassword" type="password" autocomplete="new-password" minlength="12" required></div><div class="portal-password-note">Al menos 12 caracteres. Puedes utilizar una frase fácil de recordar.</div><button type="submit" class="btn btn-primary v4-login-button">Guardar y entrar</button><button type="button" class="btn btn-secondary" data-action="logout">Salir</button>';}
    else {form.id=portalSetup?'portal-setup-form':'login-form';form.innerHTML=`${portalSetup?'<div><label class="label" for="admin-first-name">Nombre</label><input class="field" id="admin-first-name" name="firstName" autocomplete="given-name" required></div><div><label class="label" for="admin-last-name">Apellidos</label><input class="field" id="admin-last-name" name="lastName" autocomplete="family-name"></div>':''}<div><label class="label" for="login-email">Email</label><input class="field" id="login-email" name="email" type="email" autocomplete="username" required></div><div><label class="label" for="login-password">Contraseña</label><input class="field" id="login-password" name="password" type="password" autocomplete="${portalSetup?'new-password':'current-password'}" ${portalSetup?'minlength="12" maxlength="128"':''} required></div><button class="btn btn-primary v4-login-button" type="submit">${portalSetup?'Crear cuenta de administración':'Entrar en Marquee Flow'} ${icon('arrowRight','icon-sm')}</button>`;}
    card.querySelector('.login-note').innerHTML=`${icon('lock','icon-sm')}<span>Acceso personal. Cada finca consulta exclusivamente sus eventos y documentos. Si necesitas recuperar el acceso, contacta con Marquee.</span>`;
    if(portalSetup&&portalSetupEmail){const emailInput=document.getElementById('login-email');if(emailInput){emailInput.value=portalSetupEmail;emailInput.readOnly=true;}}
  };
  const portalOriginalNav=v4NavGroups;
  v4NavGroups=function(user){const groups=portalOriginalNav(user);groups.push({label:'Histórico',items:[['cancelled','Eventos cancelados','archive'],['completed','Eventos realizados','checkCircle']]});if(user.role==='VENUE_USER')groups.push({label:'Resultados',items:[['statistics','Estadísticas','chart']]});return groups;};
  const portalOriginalRender=renderShell;
  renderShell=function(){
    if(!portalReady||portalAccount?.mustChangePassword)return renderLogin();
    portalOriginalRender();if(!currentUser())return;
    document.querySelector('[data-action="reset-demo"]')?.remove();
    const sidebarStatus=document.querySelector('.v4-sidebar-status');if(sidebarStatus)sidebarStatus.innerHTML=`<div class="v4-status-line"><span>${icon('checkCircle','icon-sm')} Datos compartidos</span><strong>Conectado</strong></div><div class="v4-status-line"><span>${icon('archive','icon-sm')} Eventos archivados</span><strong>Conservados</strong></div>`;
    document.querySelector('.v4-top-status span:last-child')?.replaceChildren(document.createTextNode('Datos compartidos'));
    const newVenue=document.querySelector('[data-action="new-venue"]');if(newVenue){newVenue.dataset.action='portal-new-space';newVenue.innerHTML=icon('plus','icon-sm')+' Nueva finca o espacio';}
    const userPassword=document.querySelector('#user-form input[name="password"]');if(userPassword){userPassword.value='';userPassword.required=false;userPassword.minLength=12;userPassword.maxLength=128;userPassword.autocomplete='new-password';userPassword.placeholder=app.modal?.type==='newUser'?'Se generará una contraseña temporal':'Dejar en blanco para mantener';}
    const userForm=document.querySelector('#user-form');if(userForm&&!userForm.querySelector('.portal-password-note'))userForm.insertAdjacentHTML('beforeend','<p class="portal-password-note full">Las cuentas nuevas deben cambiar su contraseña al entrar. Si escribes una contraseña nueva al editar, se cerrarán sus sesiones y deberá cambiarla.</p>');
    for(const button of document.querySelectorAll('[data-action="toggle-user"]')){if(userById(button.dataset.id)?.protectedAccount){button.replaceWith(Object.assign(document.createElement('span'),{className:'badge badge-confirmed',textContent:'Administrador protegido'}));}}
    if(userForm&&userById(app.modal?.id)?.protectedAccount){for(const element of userForm.querySelectorAll('[name="role"],[name="venueId"],[name="active"],[name="password"]'))element.disabled=true;userForm.querySelector('[name="email"]').readOnly=true;userForm.insertAdjacentHTML('afterbegin','<div class="portal-notice full">Cuenta protegida: siempre activa y con permisos de administración. Su contraseña se cambia desde Mi cuenta.</div>');}
    document.querySelectorAll('[data-action="delete-event"]').forEach(button=>{button.dataset.action='portal-cancel';button.innerHTML=icon('archive','icon-sm')+' Archivar como cancelado';});
    const event=eventById(app.selectedEventId);
    if(event&&portalClosed.includes(event.status)){
      const body=document.querySelector('.drawer-body');if(body)body.insertAdjacentHTML('afterbegin',`<div class="portal-notice">Este evento está en ${event.status==='COMPLETED'?'Eventos realizados':'Eventos cancelados'}. Su expediente completo se conserva.${isAdmin()?` <button class="btn btn-secondary btn-sm" data-action="portal-reopen" data-id="${event.id}">Reabrir evento</button>`:''}</div>`);
    }
    if(app.modal?.type==='portalSpace')portalRenderSpaceForm();
    if(app.modal?.type==='portalCredentials')portalRenderCredentials();
    if(app.modal?.type==='portalCancel')portalRenderCancel();
    if(app.modal?.type==='portalPassword')portalRenderPassword();
  };
  const portalOriginalPage=renderPage;
  renderPage=function(){if(['cancelled','completed'].includes(app.page))return portalRenderArchive();return portalOriginalPage();};
  function portalRenderSpaceForm(){document.getElementById('modal-root').innerHTML=modalFrame('Nueva finca o espacio','Crea el espacio y su primera cuenta de acceso en un solo paso.',`<form id="portal-space-form" class="form-grid"><div class="full"><label class="label" for="space-name">Nombre de la finca o espacio *</label><input class="field" id="space-name" name="name" required maxlength="200" placeholder="Ej. Hacienda Los Olivos"></div><div><label class="label" for="space-town">Municipio</label><input class="field" id="space-town" name="municipality"></div><div><label class="label" for="space-province">Provincia</label><input class="field" id="space-province" name="province"></div><div class="full"><label class="label" for="space-address">Dirección</label><input class="field" id="space-address" name="address"></div><div class="full portal-first-user"><div class="section-title">Primera persona con acceso</div><p class="small muted">Su cuenta solo tendrá acceso a los eventos de este espacio.</p><div class="form-grid"><div><label class="label" for="space-first-name">Nombre *</label><input class="field" id="space-first-name" name="firstName" required></div><div><label class="label" for="space-last-name">Apellidos</label><input class="field" id="space-last-name" name="lastName"></div><div class="full"><label class="label" for="space-email">Email de acceso *</label><input class="field" id="space-email" name="email" type="email" required autocomplete="off"></div><div class="full"><label class="label" for="space-phone">Teléfono</label><input class="field" id="space-phone" name="phone" type="tel"></div></div></div><p class="portal-password-note full">Al crearla se mostrará una contraseña temporal para que puedas entregársela. Podrás añadir más personas a la misma finca desde Usuarios.</p></form>`,`<button class="btn btn-secondary" data-action="close-modal">Cancelar</button><button class="btn btn-primary" data-action="submit-external-form" data-form="portal-space-form">Crear espacio y cuenta</button>`);}
  function portalRenderCredentials(){const c=portalCredentials;if(!c)return;document.getElementById('modal-root').innerHTML=modalFrame('Cuenta creada','Facilita estos datos de acceso a la persona responsable.',`<div class="portal-credentials"><div><strong>Acceso</strong><br><code>${escapeHtml(location.origin)}</code></div><div><strong>Email</strong><br><code>${escapeHtml(c.email)}</code></div><div><strong>Contraseña temporal</strong><br><code>${escapeHtml(c.password)}</code></div></div><p class="portal-password-note">La contraseña solo se muestra ahora. Al entrar deberá elegir una nueva. Si cierras esta ventana antes de copiarla, puedes establecer otra desde Usuarios.</p>`,`<button class="btn btn-primary" data-action="close-modal">He guardado los datos</button>`);}
  function portalRenderCancel(){const event=eventById(app.modal.id);document.getElementById('modal-root').innerHTML=modalFrame('Archivar como cancelado','Se conservará todo el expediente.',`<p>${escapeHtml(event?.eventName||'')}</p><div class="portal-notice">Seguirán disponibles los presupuestos, documentos, mensajes y el histórico en Eventos cancelados. Administración podrá reabrirlo.</div>`,`<button class="btn btn-secondary" data-action="close-modal">Volver</button><button class="btn btn-primary" data-action="portal-confirm-cancel" data-id="${event.id}">Archivar evento</button>`);}
  function portalRenderPassword(){document.getElementById('modal-root').innerHTML=modalFrame('Cambiar mi contraseña','Se cerrarán las otras sesiones de tu cuenta.',`<form id="portal-password-form" class="stack"><div><label class="label">Contraseña actual</label><input class="field" name="currentPassword" type="password" autocomplete="current-password" required></div><div><label class="label">Nueva contraseña</label><input class="field" name="password" type="password" autocomplete="new-password" minlength="12" maxlength="128" required></div><div><label class="label">Repite la nueva contraseña</label><input class="field" name="confirmPassword" type="password" autocomplete="new-password" minlength="12" required></div></form>`,`<button class="btn btn-secondary" data-action="close-modal">Cancelar</button><button class="btn btn-primary" data-action="submit-external-form" data-form="portal-password-form">Guardar contraseña</button>`);}
  function portalFilterForm(search=false){return `<form id="portal-filter-form" class="portal-filters">${isOps()?`<div><label class="label" for="portal-venue">Finca o espacio</label><select class="select" id="portal-venue" name="venue"><option value="">Todos los espacios</option>${app.data.venues.map(v=>`<option value="${v.id}" ${portalFilters.venue===v.id?'selected':''}>${escapeHtml(v.name)}</option>`).join('')}</select></div>`:''}<div><label class="label" for="portal-from">Desde</label><input class="field" id="portal-from" name="from" type="date" value="${escapeHtml(portalFilters.from)}"></div><div><label class="label" for="portal-to">Hasta</label><input class="field" id="portal-to" name="to" type="date" value="${escapeHtml(portalFilters.to)}"></div>${search?`<div><label class="label" for="portal-q">Evento o cliente</label><input class="field" id="portal-q" name="q" value="${escapeHtml(portalFilters.q)}" placeholder="Buscar en el archivo"></div>`:''}<button class="btn btn-primary" type="submit">Aplicar filtros</button><button class="btn btn-secondary" type="button" data-action="portal-clear-filters">Limpiar</button></form>`;}
  function portalFilteredEvents(){return visibleEvents().filter(event=>(!portalFilters.venue||event.venueId===portalFilters.venue)&&(!portalFilters.from||event.eventDate>=portalFilters.from)&&(!portalFilters.to||event.eventDate<=portalFilters.to)&&(!portalFilters.q||`${event.eventName} ${event.finalClient}`.toLocaleLowerCase('es').includes(portalFilters.q.toLocaleLowerCase('es'))));}
  function portalRenderArchive(){const completed=app.page==='completed';const events=portalFilteredEvents().filter(e=>completed?e.status==='COMPLETED':['CANCELLED','NOT_ACCEPTED'].includes(e.status)).sort((a,b)=>b.eventDate.localeCompare(a.eventDate));return `${v4PageHead(completed?'Eventos realizados':'Eventos cancelados','El expediente completo permanece disponible para tu espacio.',isAdmin()?`<button class="btn btn-secondary" data-action="portal-export-archive" data-status="${completed?'COMPLETED':'CANCELLED'}">${icon('download','icon-sm')}Descargar esta vista</button>`:'','ARCHIVO DE EVENTOS')}<div class="portal-notice">${events.length} eventos en esta vista. Archivar conserva los presupuestos, documentos, mensajes e histórico.${isAdmin()?' Puedes reabrir un evento desde su ficha.':''}</div>${portalFilterForm(true)}<section class="card"><div class="table-wrap"><table class="data-table portal-stats-table"><thead><tr><th>Fecha</th><th>Evento / cliente</th>${isOps()?'<th>Finca</th>':''}<th>Estado</th><th>Documentación</th><th></th></tr></thead><tbody>${events.map(e=>`<tr><td>${formatDate(e.eventDate)}</td><td><button class="portal-archive-name" data-action="open-event" data-id="${e.id}">${escapeHtml(e.eventName)}</button><div class="table-sub">${escapeHtml(e.finalClient||'Cliente no indicado')}</div></td>${isOps()?`<td>${escapeHtml(venueById(e.venueId)?.name||'')}</td>`:''}<td>${statusBadge(e.status)}</td><td>${visibleBudgets(e).length} presupuestos<br><span class="table-sub">${visibleDocuments(e).length} documentos · ${e.comments.length} mensajes</span></td><td><button class="btn btn-secondary btn-sm" data-action="open-event" data-id="${e.id}">Abrir expediente</button></td></tr>`).join('')}</tbody></table>${events.length?'':'<div class="portal-empty">No hay eventos archivados con estos filtros.</div>'}</div></section>`;}
  renderStatistics=function(){
    const events=portalFilteredEvents();const quoted=events.filter(e=>e.budgetSentAt||e.budgets.some(b=>['SENT','FINAL','ARCHIVED'].includes(b.status))||e.acceptedAt||['CONFIRMED','COMPLETED'].includes(e.status));const accepted=quoted.filter(e=>e.acceptedAt||['CONFIRMED','COMPLETED'].includes(e.status));const rate=quoted.length?Math.round(accepted.length/quoted.length*100):null;
    const clients=new Map();for(const event of events){const name=(event.finalClient||'').trim();if(!name)continue;const linked=app.data.clients?.find(c=>c.id===event.clientId);const key=event.venueId+'|'+(linked?.mergedInto||linked?.id||name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('es').replace(/\s+/g,' '));const item=clients.get(key)||{name:app.data.clients?.find(c=>c.id===linked?.mergedInto)?.name||linked?.name||name,venueId:event.venueId,total:0,accepted:0,completed:0,last:''};item.total++;if(event.acceptedAt||['CONFIRMED','COMPLETED'].includes(event.status))item.accepted++;if(event.status==='COMPLETED')item.completed++;if(event.eventDate>item.last)item.last=event.eventDate;clients.set(key,item);}
    const ranked=[...clients.values()].sort((a,b)=>b.total-a.total||b.accepted-a.accepted||a.name.localeCompare(b.name));
    const metric=(label,value,note)=>`<article class="portal-metric"><span>${label}</span><strong>${value}</strong><small>${note}</small></article>`;
    return `${v4PageHead('Estadísticas','Resultados por fecha del evento y finca o espacio.','','RESULTADOS COMERCIALES')}${portalFilterForm()}<div class="portal-metrics">${metric('Peticiones recibidas',events.length,'Eventos únicos del periodo')}${metric('Peticiones presupuestadas',quoted.length,'Con propuesta enviada o aceptación')}${metric('Presupuestos aceptados',accepted.length,'Confirmados, realizados o con aceptación registrada')}${metric('Porcentaje de aceptación',rate===null?'—':rate+'%','Aceptadas / peticiones presupuestadas')}</div><div class="portal-stat-grid"><section class="card card-pad"><div class="card-title">Clientes más recurrentes</div><div class="card-desc">Se agrupan por nombre y finca. No se cuentan las versiones de un presupuesto como nuevas peticiones.</div>${ranked.slice(0,10).map(c=>`<div class="portal-rank"><div><strong>${escapeHtml(c.name)}</strong><small>${escapeHtml(venueById(c.venueId)?.name||'')} · ${c.accepted} aceptados · ${c.completed} realizados</small><div class="portal-progress"><i style="width:${Math.round(c.total/(ranked[0]?.total||1)*100)}%"></i></div></div><strong>${c.total} ${c.total===1?'evento':'eventos'}</strong></div>`).join('')||'<div class="portal-empty">Los clientes aparecerán aquí cuando se registren peticiones con cliente final.</div>'}</section><section class="card card-pad"><div class="card-title">Estado de las peticiones</div><div class="card-desc">Incluye los eventos archivados del periodo.</div>${Object.entries(STATUS).map(([key,info])=>({key,label:info.label,count:events.filter(e=>e.status===key).length})).filter(x=>x.count).map(x=>`<div class="portal-rank"><span>${escapeHtml(x.label)}</span><strong>${x.count}</strong></div>`).join('')||'<div class="portal-empty">Todavía no hay eventos en este periodo.</div>'}<div class="portal-notice" style="margin-top:18px;margin-bottom:0">La aceptación se registra cuando Marquee marca el evento como confirmado. Si se cancela después, su aceptación histórica se conserva.</div></section></div>`;
  };
  renderBackups=function(){return `${v4PageHead('Copias de seguridad','Recuperación de datos y descarga del expediente completo.',`<button class="btn btn-secondary" data-action="portal-export-all">${icon('download','icon-sm')}Descargar datos y archivos</button><button class="btn btn-primary" data-action="portal-create-backup">Crear copia ahora</button>`,'CONTINUIDAD')}<div class="portal-notice">Los eventos cancelados y realizados se conservan sin fecha de borrado. Las copias de recuperación contienen los datos y archivos; se comprueban cada hora y al archivar eventos, evitando copias redundantes. El almacenamiento del servidor debe contar además con sus copias externas.</div>${portalBackupError?'<div class="portal-error">La última copia no se completó. Los datos siguen en la base de datos. Crea una copia y revisa el almacenamiento.</div>':''}<section class="card card-pad"><div class="card-title">Copias verificadas del servidor</div><p class="card-desc">Estas copias no dependen del navegador. La restauración completa se realiza con el procedimiento documentado para evitar sobrescribir datos actuales.</p>${portalBackupList.map(b=>`<div class="portal-rank"><div><strong>${formatDateTime(b.createdAt)}</strong><small>${escapeHtml(b.reason)} · ${formatBytes(b.sizeBytes)}</small><small>SHA-256: ${escapeHtml(b.sha256.slice(0,16))}…</small></div><span class="badge badge-confirmed">Integridad verificada</span></div>`).join('')||'<div class="portal-empty">Pulsa Actualizar para consultar las copias.</div>'}<button class="btn btn-secondary" data-action="portal-refresh-backups">Actualizar</button></section>`;};
  renderSettings=function(){const s=app.data.settings;return `${v4PageHead('Configuración','Preferencias del equipo y seguridad de tu cuenta.')}<section class="card card-pad"><form id="settings-form" class="stack"><label class="check-row"><input type="checkbox" name="showCommercialToVenue" ${s.showCommercialToVenue?'checked':''}> Mostrar el comercial asignado a cada finca</label><div class="form-grid"><div><label class="label">Días sin actualización para aviso</label><input class="field" name="staleDays" type="number" min="1" max="30" value="${s.staleDays}"></div><div><label class="label">Días de espera tras presupuesto</label><input class="field" name="budgetResponseDays" type="number" min="1" max="30" value="${s.budgetResponseDays}"></div></div><button class="btn btn-primary" type="submit">Guardar preferencias</button></form></section><section class="card card-pad" style="margin-top:18px"><div class="card-title">Mi cuenta</div><p class="small muted">${escapeHtml(currentUser().email)}</p><button class="btn btn-secondary" data-action="portal-password">Cambiar contraseña</button></section>`;};
  const portalOldUsers=renderUsers;
  renderUsers=function(){return `<div class="portal-notice">Crea una finca y su primera cuenta desde Fincas. Desde aquí puedes añadir más personas al mismo espacio, editar sus accesos o desactivarlos. Los eventos y documentos se conservan al desactivar una cuenta.</div>`+portalOldUsers();};
  // Public mutations replace the demo's browser-only implementations.
  createEvent=data=>portalRun(async()=>{const result=await portalMutation('/events','POST',{...app.v4WizardDraft,...data});app.v4WizardDraft={};app.v4WizardStep=1;portalMemoryStorage.removeItem(V4_DRAFT_KEY);app.modal=null;app.page='events';app.selectedEventId=result.id;app.selectedEventTab='summary';history.replaceState(null,'','#events');renderShell();},'Petición enviada a Marquee');
  updateEventFromForm=data=>portalRun(async()=>{const ev=eventById(data.eventId);await portalMutation('/events/'+data.eventId,'PATCH',{...data,revision:ev.revision});app.modal=null;renderShell();},'Cambios guardados');
  changeEventStatus=(eventId,status)=>portalRun(async()=>{await portalMutation('/events/'+eventId,'PATCH',{status,revision:eventById(eventId).revision});renderShell();},portalClosed.includes(status)?'Evento archivado con su expediente completo':'Estado actualizado');
  changeEventPriority=(eventId,priority)=>portalRun(async()=>{await portalMutation('/events/'+eventId,'PATCH',{priority,revision:eventById(eventId).revision});renderShell();},'Prioridad actualizada');
  saveVenue=form=>portalRun(async()=>{const data=formObject(form);await portalMutation('/venues'+(data.venueId?'/'+data.venueId:''),data.venueId?'PATCH':'POST',data);app.modal=null;renderShell();},'Finca guardada');
  saveUser=form=>portalRun(async()=>{const data=formObject(form);const result=await portalMutation('/users'+(data.userId?'/'+data.userId:''),data.userId?'PATCH':'POST',{...data,active:Boolean(userById(data.userId)?.protectedAccount)||data.active==='on'});if(!data.userId){portalCredentials={email:result.user.email,password:result.temporaryPassword};app.modal={type:'portalCredentials'};}else app.modal=null;renderShell();},'Cuenta guardada');
  saveSettings=form=>portalRun(async()=>{const data=formObject(form);await portalMutation('/settings','PATCH',{...data,showCommercialToVenue:data.showCommercialToVenue==='on'});renderShell();},'Preferencias guardadas');
  addComment=form=>portalRun(async()=>{const data=formObject(form);await portalMutation('/events/'+data.eventId+'/comments','POST',{body:data.body});renderShell();},'Mensaje enviado');
  addNote=form=>portalRun(async()=>{const data=formObject(form);await portalMutation('/events/'+data.eventId+'/comments','POST',{body:data.body,internal:true});renderShell();},'Nota interna guardada');
  async function portalUpload(form,kind){return portalRun(async()=>{const data=formObject(form);const file=form.querySelector('input[type="file"]')?.files?.[0];if(!file)throw new Error('Selecciona un archivo.');if(file.size>20*1024*1024)throw new Error('El archivo supera los 20 MB.');const base64=await blobToBase64(file);await portalMutation('/events/'+data.eventId+'/files','POST',{...data,kind,base64,originalName:file.name,revision:eventById(data.eventId).revision});app.proModal=null;renderShell();},kind==='budgets'?'Presupuesto publicado':'Documento guardado');}
  uploadBudget=form=>portalUpload(form,'budgets');uploadDocument=form=>portalUpload(form,'documents');
  getFileBlob=async fileKey=>{const response=await fetch('/api/files/'+encodeURIComponent(fileKey),{credentials:'same-origin'});if(!response.ok)throw new Error('No se pudo abrir el archivo.');return response.blob();};
  renderBudgetDocumentPreview=function(event,budget){
    if(!app.v4PreviewUrl)return '<div class="portal-empty">Abriendo el documento original…</div>';
    if(budget.mimeType==='application/pdf')return `<iframe title="${escapeHtml(budget.displayName)}" src="/viewer?file=${encodeURIComponent(budget.fileKey)}" style="width:100%;height:75vh;border:0;background:white"></iframe>`;
    if(['image/png','image/jpeg'].includes(budget.mimeType))return `<img src="${app.v4PreviewUrl}" alt="${escapeHtml(budget.displayName)}" style="max-width:100%;height:auto;display:block;margin:auto">`;
    return '<div class="portal-empty">Este formato se consulta descargando el archivo original con el botón Descargar.</div>';
  };
  downloadStoredFile=async item=>{if(!item.fileKey)throw new Error('El archivo no está disponible.');downloadBlob(await getFileBlob(item.fileKey),item.originalName);};
  openV4BudgetPreview=(eventId,budgetId)=>portalRun(async()=>{const ev=eventById(eventId);const budget=ev?.budgets.find(b=>b.id===budgetId);if(!budget)throw new Error('Presupuesto no disponible.');if(app.v4PreviewUrl?.startsWith('blob:'))URL.revokeObjectURL(app.v4PreviewUrl);app.v4PreviewUrl=URL.createObjectURL(await getFileBlob(budget.fileKey));app.v4Modal={type:'budgetPreview',eventId,budgetId};renderShell();});
  downloadV4Budget=(eventId,budgetId)=>portalRun(async()=>{const budget=eventById(eventId)?.budgets.find(b=>b.id===budgetId);if(!budget)throw new Error('Presupuesto no disponible.');await downloadStoredFile(budget);});
  duplicateEvent=eventId=>{const ev=eventById(eventId);if(!ev)return;app.v4WizardDraft={...ev,eventName:ev.eventName+' (copia)',eventDate:''};app.v4WizardStep=1;app.selectedEventId=null;navigate('new-event');};
  archiveBudget=()=>toast('Se conserva el histórico','Publica una nueva versión para sustituir el presupuesto vigente. Las anteriores permanecen vinculadas al expediente.');
  async function portalLoadBackups(){const result=await portalApi('/backups');portalBackupList=result.backups;portalBackupError=result.lastBackupError;renderShell();}
  async function portalExport(status){const result=await portalApi('/export'+(status?'?status='+encodeURIComponent(status):''));downloadBlob(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}),'marquee-'+(status||'completo')+'-'+dateIso(new Date())+'.json');}
  window.addEventListener('submit',event=>{
    const form=event.target;if(!(form instanceof HTMLFormElement))return;
    const handled=['login-form','portal-setup-form','portal-password-form','portal-space-form','portal-filter-form','v4-task-form','v4-info-request-form','v4-next-action-form','v4-revision-form','pro-upload-form'];
    if(!handled.includes(form.id))return;event.preventDefault();event.stopImmediatePropagation();
    const data=formObject(form);
    if(form.id==='portal-filter-form'){if(data.from&&data.to&&data.from>data.to)return toast('Revisa las fechas','La fecha inicial debe ser anterior a la final.','error');Object.assign(portalFilters,{venue:data.venue||'',from:data.from||'',to:data.to||'',q:data.q||'',eventType:data.eventType||''});portalDirty=false;renderShell();return;}
    if(form.id==='pro-upload-form'){portalUpload(form,form.dataset.kind==='BUDGET'?'budgets':'documents');return;}
    portalRun(async()=>{
      if(['login-form','portal-setup-form','portal-password-form'].includes(form.id)){
        if(form.id==='portal-password-form'&&data.password!==data.confirmPassword)throw new Error('Las contraseñas nuevas no coinciden.');
        const result=await portalApi(form.id==='login-form'?'/login':form.id==='portal-setup-form'?'/bootstrap':'/password','POST',{...data,...(form.id==='portal-setup-form'?{token:portalSetupToken}:{})});
        portalCsrf=result.csrf;portalAccount=result.user;portalSetup=false;app.session=null;app.data=loadData();app.modal=null;app.selectedEventId=null;app.v4WizardDraft={};portalMemoryValues.clear();
        if(!portalAccount.mustChangePassword){await portalReload(false);app.page='dashboard';history.replaceState(null,'','#dashboard');}renderShell();return;
      }
      if(form.id==='portal-space-form'){
        const result=await portalMutation('/venues-with-user','POST',{venue:{name:data.name,municipality:data.municipality,province:data.province,address:data.address,contactName:[data.firstName,data.lastName].filter(Boolean).join(' '),phone:data.phone,email:data.email},user:{firstName:data.firstName,lastName:data.lastName,email:data.email}});
        portalCredentials={email:result.user.email,password:result.temporaryPassword};app.modal={type:'portalCredentials'};renderShell();return;
      }
      if(form.id==='v4-task-form'||form.id==='v4-info-request-form')await portalMutation('/events/'+data.eventId+'/tasks','POST',{...data,kind:form.id==='v4-task-form'?'tasks':'infoRequests',revision:eventById(data.eventId).revision});
      if(form.id==='v4-next-action-form')await portalMutation('/events/'+data.eventId,'PATCH',{...data,revision:eventById(data.eventId).revision});
      if(form.id==='v4-revision-form'){await portalMutation('/events/'+data.eventId+'/comments','POST',{body:'Solicitud de modificación de presupuesto: '+(data.body||data.message||'')});app.v4Modal=null;}
      renderShell();
    });
  },true);
  const portalClickActions=new Set(['logout','toggle-user','mark-all-read','open-notification','v4-toggle-task','v4-toggle-info','v4-mark-action-done','portal-new-space','portal-cancel','portal-confirm-cancel','portal-reopen','portal-clear-filters','portal-create-backup','portal-refresh-backups','portal-export-archive','portal-export-all','portal-password','reset-demo','confirm-reset-demo','confirm-delete-event','trigger-import-backup','confirm-restore-snapshot','delete-snapshot']);
  window.addEventListener('click',event=>{
    const target=event.target.closest?.('[data-action]');if(!target)return;const action=target.dataset.action;
    if(action==='close-modal'&&app.modal?.type==='portalCredentials')portalCredentials=null;
    if(action==='navigate'&&target.dataset.page==='backups'){setTimeout(()=>portalRun(portalLoadBackups),0);}
    if(!portalClickActions.has(action))return;event.preventDefault();event.stopImmediatePropagation();
    if(action==='portal-new-space'){app.modal={type:'portalSpace'};renderShell();return;}
    if(action==='portal-cancel'){app.modal={type:'portalCancel',id:target.dataset.id||app.selectedEventId};renderShell();return;}
    if(action==='portal-password'){app.modal={type:'portalPassword'};renderShell();return;}
    if(action==='portal-clear-filters'){Object.assign(portalFilters,{venue:'',from:'',to:'',q:''});renderShell();return;}
    if(['reset-demo','confirm-reset-demo','confirm-delete-event','trigger-import-backup','confirm-restore-snapshot','delete-snapshot'].includes(action)){toast('Datos conservados','El portal no permite borrar expedientes ni reemplazar los datos desde el navegador.');return;}
    portalRun(async()=>{
      if(action==='logout'){auditReset();await portalApi('/logout','POST',{});portalCsrf=null;portalAccount=null;app.session=null;app.data=loadData();app.selectedEventId=null;app.modal=null;app.v4Modal=null;app.v4WizardDraft={};portalCredentials=null;portalMemoryValues.clear();Object.assign(portalFilters,{venue:'',from:'',to:'',q:''});history.replaceState(null,'',location.pathname);renderShell();return;}
      if(action==='toggle-user'){const user=userById(target.dataset.id);await portalMutation('/users/'+user.id,'PATCH',{active:!user.active});}
      if(action==='mark-all-read')await portalMutation('/notifications/read','POST',{});
      if(action==='open-notification'){const item=app.data.notifications.find(n=>n.id===target.dataset.id);await portalMutation('/notifications/read','POST',{id:item.id});if(item.eventId){app.selectedEventId=item.eventId;app.selectedEventTab=item.type==='BUDGET_AVAILABLE'?'budgets':'summary';}}
      if(['v4-toggle-task','v4-toggle-info'].includes(action)){const ev=eventById(target.dataset.eventId);const kind=action==='v4-toggle-task'?'tasks':'infoRequests';const task=ev[kind].find(t=>t.id===target.dataset.id);await portalMutation('/events/'+ev.id+'/tasks','POST',{kind,id:task.id,done:!task.done,revision:ev.revision});}
      if(action==='v4-mark-action-done'){const ev=eventById(target.dataset.id);await portalMutation('/events/'+ev.id,'PATCH',{nextAction:'',nextActionDue:'',waitingOn:'NONE',revision:ev.revision});}
      if(action==='portal-confirm-cancel'||action==='portal-reopen'){const ev=eventById(target.dataset.id);await portalMutation('/events/'+ev.id,'PATCH',{status:action==='portal-reopen'?'PENDING_REVIEW':'CANCELLED',revision:ev.revision});app.modal=null;}
      if(action==='portal-create-backup'){await portalApi('/backups','POST',{});await portalLoadBackups();return;}
      if(action==='portal-refresh-backups'){await portalLoadBackups();return;}
      if(action==='portal-export-all'||action==='portal-export-archive'){await portalExport(target.dataset.status);return;}
      renderShell();
    });
  },true);
  window.addEventListener('change',event=>{const target=event.target;if(target.matches?.('[data-v4-change="waitingOn"]')){event.preventDefault();event.stopImmediatePropagation();portalRun(async()=>{await portalMutation('/events/'+target.dataset.id,'PATCH',{waitingOn:target.value,revision:eventById(target.dataset.id).revision});renderShell();});}},true);
  window.addEventListener('input',event=>{if(event.target.closest?.('form'))portalDirty=true;},true);
  window.addEventListener('beforeunload',event=>{if(portalDirty||portalBusy){event.preventDefault();event.returnValue='';}});
  window.addEventListener('hashchange',()=>{const token=new URLSearchParams(location.hash.slice(1)).get('setup');if(token){portalSetupToken=token;history.replaceState(null,'',location.pathname);if(!portalAccount)renderShell();}});
  const portalBoot=async()=>{try{const result=await portalApi('/session');portalCsrf=result.csrf;portalAccount=result.user;portalSetup=result.setupRequired;portalSetupEmail=result.setupEmail||'';if(portalAccount&&!portalAccount.mustChangePassword)await portalReload(false);portalReady=true;const page=location.hash.slice(1);if(currentUser()&&page)app.page=safePage(page,currentUser());renderShell();}catch(error){portalReady=true;renderLogin();const box=document.getElementById('login-error');box.style.display='block';box.textContent='No se pudo conectar con el servidor. Recarga la página para volver a intentarlo.';}};
  portalBoot();
  setInterval(async()=>{if(!portalAccount||portalAccount.mustChangePassword||portalBusy||portalDirty||document.hidden||app.modal||app.selectedEventId||app.page==='new-event')return;try{const {data}=await portalApi('/state');if(data.revision!==app.data.revision){app.data=data;ensureV4Data();renderShell();}}catch{}},15000);
